### ISSUE TITLE
Change reviewer invite template

### ISSUE THREAD

**Issue by shicks-seismo** [WeAreSeismica/seismica-ojs#10]
Dear [name], 

I hope this email finds you well.

I'm acting as Editor for a new submission to Seismica, which is entitled "[title]". The authors are: [list of authors]. I thought that you would be an excellent reviewer for this manuscript because of your expertise in [...]. The submission's abstract is inserted below, and I hope that you will please consider undertaking this important task for us.

As you may know, Seismica [http://www.seismica.org/] is a new journal, giving the field of Seismology and Earthquake Science its first Diamond Open-Access offering, which means that it is free to publish and free to read without a subscription. Seismica is therefore run entirely by a volunteer community, and we rely on the hard work of potential peer reviewers like yourself to support this new accessible, transparent, respectful, credible, and progressive publishing initiative for our community.
To learn more about Seismica and the roles and responsibilities of our peer reviewers, please visit: https://seismica.library.mcgill.ca/reviewer-guidelines. You can also find our Competing Interests policy here: https://seismica.library.mcgill.ca/policies.

Please log into the journal website by Response Due Date to indicate whether you will undertake the review or not, as well as to access the submission and record your review and recommendation. The website is https://seismica.library.mcgill.ca/.

The review itself is due [Review Due Date], but please do let me know if you would have any problems with this proposed timeframe.

If you do not have your username and password for the journal's website, you can use this link to reset your password (which will then be emailed to you along with your username). https://seismica.library.mcgill.ca/login/lostPassword

Submission URL: URL

Thank you in advance for considering this request, and please don't hesitate to contact me on the email address below with any queries or concerns.

[Editor name]
[Editor institution]

**Comment by hfmark** [comment]
I updated the `REVIEW_REQUEST` template using this, with a few small edits. OJS doesn't have a way to automatically add author names to reviewer emails, though an editor could manually add that info (as long as the submission isn't double-anonymous). I also amended the open-ended "because of your expertise in [...]" - again, editors can add as much as they want, but it seems risky to leave blank spaces to fill in case people send a request without reading the template super carefully first.
