### ISSUE TITLE
Place PDF/XML buttons on top for small viewports

### ISSUE THREAD

**Issue by martijnende** [WeAreSeismica/seismica-ojs#12]
For large viewports the PDF and XML article buttons are positioned on the right of the article abstract. For small viewports the buttons move down below the abstract and references, rendering them virtually hidden for users who don't scroll past the (long) reference list.

**Comment by ThomasLecocq** [comment]
this line in the JS file (provided jquery is loaded) works by copying the Galley divs below the abstract: (not tested in the real stuff, I just played in my browser - developer view for now !)


`$("div.item.galleys").appendTo($(".abstract"));`

![image](https://user-images.githubusercontent.com/916937/201383507-175fc77a-5bf0-4a50-8ef6-ffa6df9df0ca.png)

**Comment by ThomasLecocq** [comment]
this way it should be safe:
```javascript
$(document).ready(function() {
    $("div.item.galleys").appendTo($(".abstract"));
  });
```
ideally, it'd be good to check we are on an /article/ page, sthg like;
```javascript
$(document).ready(function() {
    if (window.location.href.indexOf("article") > -1) {
    	$("div.item.galleys").appendTo($(".abstract"));
    	}
  });
```
or

```javascript
$(document).ready(function() {
   if (/article/.test(window.location.href)) {
    	$("div.item.galleys").appendTo($(".abstract"));
    	}
  });
```

**Comment by ThomasLecocq** [comment]
solution 2 above implemented on the main site - not suuupppper clean (bit of too much padding), but I think it's functional

@martijnende

**Comment by ThomasLecocq** [comment]
WIP, the code above MOVES the elements, I want to COPY them

**Comment by ThomasLecocq** [comment]
final version:

```javascript
$(document).ready(function() {
    if (window.location.href.indexOf("article") > -1) {
        var $button = $("div.item.galleys").clone();
    	$(".abstract").append($button);
    	}
  });
```
implemented on the production site !

**Comment by ThomasLecocq** [comment]
@martijnende I don't have the rights to close issues :) feel free if you find the solution OK :-)

**Comment by martijnende** [comment]
Looks good. Thanks!
