### ISSUE TITLE
orcid request emails to authors have bad links

### ISSUE THREAD

**Issue by hfmark** [WeAreSeismica/seismica-ojs#14]
Authors/contributors get an automated email asking them to connect their orcid to a submission if the submitting author checks a certain box. With the editorial, people tried these links and got a 404 error.

**Comment by hfmark** [comment]
I just checked the email templates for these (ORCID_COLLECT_AUTHOR_ID and ORCID_REQUEST_AUTHOR_AUTHORIZATION) and it looked like the problem is that the embedded links are prefaced with a settings url. The actual shortcode for the url is in theory ok (personally I was able to link my orcid by deleting the excess bits of the url from the email link). I can't get rid of the preface part; when I try to do that and save it, OJS just adds it back in.

**Comment by martijnende** [comment]
This should now be fixed (on the McGill side of things). In the rare case that an author might find a broken link, they can get a working link here: http://link.seismica.org/
